//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMES_MARKET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Games_MarketEntities : DbContext
    {
        public Games_MarketEntities()
            : base("name=Games_MarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<capturas> capturas { get; set; }
        public virtual DbSet<claves> claves { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
        public virtual DbSet<descuentos> descuentos { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<juegos> juegos { get; set; }
        public virtual DbSet<plataformas> plataformas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<valoraciones> valoraciones { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    }
}
