//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMES_MARKET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int id_venta { get; set; }
        public int id_clave { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public string tarj { get; set; }
        public string tarj_mes { get; set; }
        public string tarj_ano { get; set; }
    
        public virtual claves claves { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
